### ISSUE TITLE
Config not highlight if used same directive

### ISSUE THREAD

**Issue by Shkiperon** [ffloimair/vscode-asterisk-syntax#2]
Hello.
If in Asterisk configuration used construction like this:

```
exten => s,1,NoOp()
 same => n,Set(PRENUM=${CUT(MEMBERINTERFACE,/,2)})
 same => n,Set(NUM=${CUT(PRENUM,@,1)})

```
the lines with same directive not highlight functions, constructions, etc.
Can you update highlight rules?

**Comment by ffloimair** [comment]
Hi! Thanks for filing this issue.
There are quite some things that no longer work as expected, this is one of them.
I will try to fix this and other issues that I have found shortly.

**Comment by ffloimair** [comment]
Hi!

Sorry that this took so long. I have had a struggle to get my extension updated on the Market place.
The fix you asked for is in commit https://github.com/ffloimair/vscode-asterisk-syntax/commit/24232d052a8b92f540f1b712e7b0a4c5d7e76fc6 and is released together with version 1.0.2 today.

**Comment by ffloimair** [comment]
Just realized that I have uncommented the relevant section in the commit I have published. Sorry for that. Need to reissue this.

**Comment by Shkiperon** [comment]
Hello. Is any news about this issue?

**Comment by ffloimair** [comment]
Hi! Sorry for the long wait. I will retest and try to publish in the next days.
This somehow got lost in my schedule.

**Comment by ffloimair** [comment]
Just to give you an update. I am still struggling a bit with tmLanguage syntax.
Right now I either get "exten" lines working or "same" lines, but not both at the same time.
I need to put some more time into this.

**Comment by Shkiperon** [comment]
Hello. May be this example will help: https://github.com/peacefixation/vscode-asterisk/blob/master/syntaxes/asterisk.tmLanguage

**Comment by ffloimair** [comment]
extension is now deprecated. Please use https://marketplace.visualstudio.com/items?itemName=peacefixation.asterisksyntaxhighlighter instead.
